# Generated by Django 4.1.3 on 2022-12-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spareparts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=126)),
                ("material_cost", models.FloatField(default=0.0)),
                ("build_hours", models.IntegerField(blank=True, default=0, null=True)),
                ("is_sold", models.BooleanField(default=False)),
                ("sold_price", models.IntegerField(default=0)),
                ("service_fee", models.IntegerField(default=200000)),
                ("notes", models.TextField(default="")),
            ],
            options={
                "ordering": ["build_date"],
            },
        ),
        migrations.CreateModel(
            name="SoldOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("is_sold", models.BooleanField(default=False)),
                ("markup", models.FloatField(default=0.4)),
                ("material_cost", models.IntegerField(default=0)),
                ("service_cost", models.IntegerField(default=200000)),
                (
                    "build_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="build_log.buildlog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_date", models.DateField(blank=True, null=True)),
                ("stock_out", models.IntegerField(default=0)),
                ("personal_use", models.BooleanField(default=False)),
                ("notes", models.TextField(default="-")),
                (
                    "build_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="build_log.buildlog",
                    ),
                ),
                (
                    "sparepart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spareparts.sparepart",
                    ),
                ),
            ],
        ),
    ]
